"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'javascript','html', 'python', 'misc']
 " let g:vundles=['general', 'programming']
  let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
endif

"syntax on
"color dracula
" Customize to your needs...

  Plugin 'vim-airline/vim-airline-themes'
  Plugin 'dracula/vim'
  "let g:base16_shell_path=base16-builder/output/shell/
  "set background=light
  "colorscheme base16-default-light
